exports.Serializer        = require('./serializer')
exports.Resource          = require('./resource')
exports.Resource.Mongoose = require("./resource/mongoose")
exports.Api               = require('./api')
exports.http              = require('./http')
exports.Paginator         = require('./paginator')
exports.Cache             = require('./cache')
exports.exceptions        = require('./exceptions')
